imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    assets_version: v2.0.0

framework:
    esi: ~
    fragments:
        path: /_proxy
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version%
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 31536000
        cookie_domain: %domain%
        name: 'Certificationy'
        handler_id:  snc_redis.session.handler
        gc_probability: 0
    http_method_override: true

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ga_tracking: %google_analytics_id%
    form:
        resources:
            - '::form_layout.html.twig'

monolog:
    channels: [ "github", "certy" ]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    delivery_address: no-reply@certificationy.com

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Certificationy\Bundle\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: false
        form:
            type: certificationy_user_registration

hwi_oauth:
    firewall_name: main
    connect:
        confirmation: true
        account_connector: certificationy.user.provider.fosub_bridge

    resource_owners:
        github:
            type: github
            client_id: %github_client_id%
            client_secret: %github_client_secret%
            scope: "user:email"

    fosub:
        username_iterations: 30
        properties:
            github: githubID

braincrafted_bootstrap:
    output_dir: %kernel.root_dir%/Resources/bootstrap-custom/bootstrap.less
    assets_dir: %kernel.root_dir%/Resources/assets/bootstrap/less/bootstrap.less
    jquery_path: %kernel.root_dir%/Resources/assets/jquery/jquery.js
    less_filter: less
    customize:
        variables_file: %kernel.root_dir%/../src/Certificationy/Bundle/WebBundle/Resources/private/less/variable.less
    auto_configure:
        assetic: false
        twig: false
        knp_menu: true
        knp_paginator: true

jms_serializer:
    metadata:
        debug: %kernel.debug%

doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options:
                password: %mongodb_password%
    default_database: %mongodb_collection%
    document_managers:
        default:
            auto_mapping: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%/%redis_default_client%

        session:
            type: predis
            alias: session
            dsn: %redis_dsn%/%redis_session_client%

        counter:
            type: predis
            alias: counter
            dsn: %redis_dsn%/%redis_counter_client%
    session:
        client: session
        prefix: session:main
        use_as_default: true

certificationy_certy:
    debug: %kernel.debug%
    provider:
        file:
            root_dir: %kernel.root_dir%/Resources/certificationy-data
    calculator:
        class: Certificationy\Component\Certy\Calculator\Calculator
        delegator: ~ #rabbitmq

services:
    twig.extension.i18n:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
